language: php

php:
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
    - |
      if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
        composer install --ignore-platform-reqs
      else
        composer install
      fi

after_success:
  - travis_retry php bin/php-coveralls -v
