<?php

/*
 * This file is part of the Access package.
 *
 * (c) Tim <me@justim.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Access;

use Access\Driver\DriverInterface;

/**
 * Debug your query
 *
 * @author Tim <me@justim.net>
 */
class DebugQuery
{
    /**
     * @var Query
     */
    private Query $query;

    public function __construct(Query $query)
    {
        $this->query = $query;
    }

    /**
     * Get a "runnable" version of the query
     *
     * NOTE: this should not be used in production
     *
     * @return string|null Runnable query
     */
    public function toRunnableQuery(?DriverInterface $driver = null): ?string
    {
        $driver = Database::getDriverOrDefault($driver);

        $sql = $this->query->getSql($driver);

        if ($sql === null) {
            return null;
        }

        $values = $this->query->getValues($driver);

        /** @var mixed $value */
        foreach ($values as $placeholder => $value) {
            $sql = preg_replace("/:$placeholder\b/", $driver->getDebugSqlValue($value), $sql);

            /**
             * The placeholders are generated by us, we can use a simple regex to replace them
             * and the result will always be a valid string
             */
            assert(is_string($sql));
        }

        return $sql;
    }
}
